---
driver:
  name: vagrant
  pre_create_command: vagrant box update --box $KITCHEN_PLATFORM_NAME
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  retry_on_exit_code:
  - 35 # 35 is the exit code signaling that the node is rebooting
  max_retries: 1
  client_rb:
    exit_status: :enabled # Opt-in to the standardized exit codes
    client_fork: false  # Forked instances don't return the real exit code
    environment: _default
  product_name: chef
  product_version: 14

verifier:
  name: inspec

platforms:
  - name: bento/centos-7

suites:
  - name: automatev2
    driver:
      customize:
        memory: 2560
    run_list:
      - recipe[chef_software::chef_automatev2]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

  - name: server
    run_list:
      - recipe[chef_software::chef_server]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

  - name: supermarket
    run_list:
      - recipe[chef_software::chef_supermarket]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
