AllCops:
  Exclude:
    - vendor/**/*
    - Guardfile
  TargetRubyVersion: 2.5

ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
PerceivedComplexity:
  Enabled: false
